set -g default-command "${SHELL}"
set -g history-limit   500000
#set -g default-terminal "screen-256color"
set -s escape-time 0
set -g mode-keys vi
set-option -g prefix C-Space
set -g base-index 1

set-option -g mouse off

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

set-window-option -g xterm-keys on 

#bind-key '^[[1;3D' backward-word
#bind-key '^[[1;3C' forward-word

set-option -g status-style bg=colour235,fg=colour136,default 

# window title colors
set-window-option -g window-status-style fg=colour244,bg=default,dim

# active window
set-window-option -g window-status-current-style fg=colour15,bg=colour98,bright

# pane border
set-option -g pane-border-style fg=colour235
set-option -g pane-active-border-style fg=colour98

# message text
set-option -g message-style bg=colour231,fg=colour232

set -g status-justify left


setw -g pane-border-status bottom
setw -g pane-border-format '─'

set -as terminal-overrides '*:Se=\e[5 q'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


